randomRickandMorty = {
  rickAndMortyCharacter: function () {

    randmArray = [
      'Abradolf Lincler',
      'Agent Gribbles',
      'Alan Rails',
      'Alien Parasites',
      'Amish Cyborg',
      'Annie',
      'Ants in my Eyes Johnson',
      'Armagheadon',
      'Armothy',
      'Arthricia',
      'Associates of Rick',
      'Baby Legs',
      'Balthrema',
      'Beta VII',
      'Beta-Seven',
      'Beth Smith',
      'Birdperson',
      'Blim Blam',
      'Bobby Moynihan',
      'Brad',
      'Bruce',
      'Butter Robot',
      'Campaign Manager Morty',
      'Coach Feratu',
      'Concerto',
      'Cool Rick',
      'Cop Morty',
      'Cop Rick',
      'Cornvelious Daniel',
      'Courier Flap',
      'Cousin Nicky',
      'Crab Spider',
      'Crocubot',
      'Cronenberg Morty',
      'Cronenberg Rick',
      'Davin',
      'Diane Sanchez',
      'Doofus Rick',
      'Dr. Glip-Glop',
      'Dr. Wong',
      'Dr. Xenon Bloom',
      'Duck With Muscles',
      'Dumb Rick',
      'Elon Tusk',
      'Ethan',
      'Eye Patch Morty',
      'Eyehole Man',
      'Fart',
      'Frank Palicky',
      'Gaia',
      'Galactic Federation President',
      'Ghost in a Jar',
      'Glexo Slim Slom',
      'Glootie',
      'Jacob',
      'Jaguar',
      'Jan-Michael Vincent',
      'Jerry Smith',
      'Jessica',
      'Joyce Smith',
      'King Flippy Nips',
      'King Jellybean',
      'Krombopulos Michael',
      'Leonard Smith',
      'Logic',
      'Lucius Needful',
      'Maximums Rickimus',
      'Michael Thompson',
      'Million Ants',
      'Mortimer Morty Smith Jr.',
      'Morty Smith',
      'Mr. Goldenfold',
      'Mr. Lucius Needful',
      'Mr. Meeseeks',
      'Mr. Poopybutthole',
      'Mrs. Pancakes',
      'Nancy',
      'Nathan',
      'Noob Noob',
      'Paul Fleishman',
      'Pencilvester',
      'Phoenixperson',
      'Photography Cyborg',
      'Pichael Thompson',
      'Pickle Rick',
      'Poncho',
      'Prince Nebulon',
      'Principal Gene Vaagena',
      'Professor Tock',
      'Real Fake Doors Salesman',
      'Reggie',
      'Reverse Giraffe',
      'Revolio Clockberg, Jr.',
      'Gearhead',
      'Rick Sanchez',
      'Ruben',
      'Scary Terry',
      'Scroopy Noopers',
      'Self-Congratulatory Jerry',
      'Shane',
      'Sleepy Gary',
      'Snuffles',
      'Space Beth',
      'Squanchy',
      'Stacy',
      'Steve',
      'Summer Smith',
      'Supernova',
      'Taddy Mason',
      'Talking Cat',
      'Tammy Gueterman',
      'Galactic Federation Agent',
      'The Agency Director',
      'The President',
      'The President of the Miniverse',
      'Thomas Tommy Lipkip',
      'Tinkles',
      'Tiny Rick',
      'Toby Matthews',
      'Tony',
      'Tricia Lange',
      'Unity',
      'Vance Maximus',
      'Renegade Starsoldier',
      'Water-T',
      'Zeep Xanflorp'
    ];

    var character = randmArray[Math.floor(Math.random() * randmArray.length)];
    return character;
  }
};

module.exports = randomRickandMorty;